export type LanguageCode = 'en' | 'ur' | 'pa' | 'sd' | 'ps' | 'bal' | 'skr' | 'hnd' | 'ks'

export type LanguageOption = {
  code: LanguageCode
  label: string
  nativeLabel: string
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'پنجابی' },
  { code: 'sd', label: 'Sindhi', nativeLabel: 'سنڌي' },
  { code: 'ps', label: 'Pashto', nativeLabel: 'پښتو' },
  { code: 'bal', label: 'Balochi', nativeLabel: 'بلوچی' },
  { code: 'skr', label: 'Saraiki', nativeLabel: 'سرائیکی' },
  { code: 'hnd', label: 'Hindko', nativeLabel: 'ہندکو' },
  { code: 'ks', label: 'Kashmiri', nativeLabel: 'کٲشُر' },
]

const english: Record<string, string> = {
  chooseLanguage: 'Choose language',
  appLanguage: 'App language',
  save: 'Save',
  cancel: 'Cancel',
  welcomeSubtitleClient: 'Book venues, food, decor & more.',
  welcomeSubtitleVendor: 'List services & get orders.',
  bookRoleTitle: 'I want to Book',
  vendorRoleTitle: 'I am a Vendor',
  continueAsGuest: 'Continue as Guest',
  guestDescription: 'Explore vendors, packages, and features without signing up.',
  currentLocation: 'Current Location',
  locationUnavailable: 'Location unavailable',
  detectingLocation: 'Detecting location...',
  all: 'All',
  categories: 'Categories',
  live: 'Live',
  topRated: 'Top Rated',
  nearbyVendors: 'Nearby Vendors',
  seeAll: 'See All',
  loadingVendors: 'Loading vendors...',
  startingFrom: 'Starting From',
  guests: 'Guests',
  guestModeTitle: 'Bookings locked in guest mode',
  signInToUseChat: 'Sign in to use chat features.',
  dashboard: 'Dashboard',
  vendorControlPanel: 'Vendor Control Panel',
  totalRevenue: 'Total Revenue',
  confirmedBookings: 'Confirmed Bookings',
  accepted: 'Accepted',
  rejected: 'Rejected',
  pending: 'Pending',
  avgRating: 'Avg Rating',
  pendingBookings: 'Pending Bookings',
  loadingRecentOrders: 'Loading recent orders...',
  noPendingBookings: 'No pending bookings',
  recentReviews: 'Recent Reviews',
  myBookingsTitle: 'My Bookings',
  trackBookings: 'Track and manage your event bookings',
  bookingsLocked: 'Bookings locked in guest mode',
  signInToViewBookings: 'Sign in to view and manage your bookings.',
  youAreGuest: 'You are browsing as a guest',
  bookingHistoryAfterSignIn: 'Booking history and booking management are available after sign in.',
  loadingBookings: 'Loading bookings...',
  noBookingsFound: 'No bookings found',
  startBooking: 'Start booking vendors for your event',
  noStatusBookings: 'No bookings at the moment',
  createAccount: 'Create Your Account',
  registerBusiness: 'Register Your Business',
  fullName: 'Full Name',
  emailAddress: 'Email Address',
  phoneNumber: 'Phone Number',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  signUp: 'Sign Up',
  creatingAccount: 'Creating account...',
  alreadyHaveAccount: 'Already have an account?',
  loginHere: 'Login Here',
  forgotPassword: 'Forgot Password?',
  preferences: 'Preferences',
  privacySecurity: 'Privacy & Security',
  appNotifications: 'App Notifications',
  receiveAlerts: 'Receive alerts for new orders and messages',
  settings: 'Settings',
  saveSettings: 'Save Settings',
  aboutMe: 'About Me',
  myBookings: 'My Bookings',
  paymentMethods: 'Payment Methods',
  helpCenter: 'Help Center',
  logOut: 'Log Out',
  deleteAccount: 'Delete Account Permanently',
  banquets: 'Banquets',
  catering: 'Catering',
  photoShoot: 'Photo Shoot',
  parlor: 'Parlor',
  searchPlaceholder: 'Search venues, catering, parlors...',
}

const urdu: Record<string, string> = {
  chooseLanguage: 'زبان منتخب کریں',
  appLanguage: 'ایپ کی زبان',
  save: 'محفوظ کریں',
  cancel: 'منسوخ کریں',
  welcomeSubtitleClient: 'ویڈیوز، کھانا، ڈیکور اور مزید بک کریں۔',
  welcomeSubtitleVendor: 'سروسز شامل کریں اور آرڈرز حاصل کریں۔',
  bookRoleTitle: 'میں بک کرنا چاہتا/چاہتی ہوں',
  vendorRoleTitle: 'میں وینڈر ہوں',
  continueAsGuest: 'بطور مہمان جاری رکھیں',
  guestDescription: 'بغیر سائن اپ کے وینڈرز، پیکیجز اور فیچرز دیکھیں۔',
  currentLocation: 'موجودہ مقام',
  locationUnavailable: 'مقام دستیاب نہیں',
  detectingLocation: 'مقام معلوم کیا جا رہا ہے...',
  all: 'سب',
  categories: 'اقسام',
  live: 'فعال',
  topRated: 'بہترین ریٹیڈ',
  nearbyVendors: 'قریبی وینڈرز',
  seeAll: 'سب دیکھیں',
  loadingVendors: 'وینڈرز لوڈ ہو رہے ہیں...',
  startingFrom: 'شروع قیمت',
  guests: 'مہمان',
  guestModeTitle: 'گیسٹ موڈ میں بکنگ بند ہے',
  signInToUseChat: 'چیٹ استعمال کرنے کے لیے سائن اِن کریں۔',
  dashboard: 'ڈیش بورڈ',
  vendorControlPanel: 'وینڈر کنٹرول پینل',
  totalRevenue: 'کل آمدنی',
  confirmedBookings: 'کنفرم شدہ بکنگز',
  accepted: 'قبول شدہ',
  rejected: 'مسترد',
  pending: 'زیر التوا',
  avgRating: 'اوسط ریٹنگ',
  pendingBookings: 'زیر التوا بکنگز',
  loadingRecentOrders: 'حالیہ آرڈرز لوڈ ہو رہے ہیں...',
  noPendingBookings: 'کوئی زیر التوا بکنگ نہیں',
  recentReviews: 'حالیہ جائزے',
  myBookingsTitle: 'میری بکنگز',
  trackBookings: 'اپنی ایونٹ بکنگز کو ٹریک اور منظم کریں',
  bookingsLocked: 'گیسٹ موڈ میں بکنگز بند ہیں',
  signInToViewBookings: 'اپنی بکنگز دیکھنے اور منظم کرنے کے لیے سائن اِن کریں۔',
  youAreGuest: 'آپ بطور مہمان براؤز کر رہے ہیں',
  bookingHistoryAfterSignIn: 'بکنگ ہسٹری اور منیجمنٹ سائن اِن کے بعد دستیاب ہیں۔',
  loadingBookings: 'بکنگز لوڈ ہو رہی ہیں...',
  noBookingsFound: 'کوئی بکنگ نہیں ملی',
  startBooking: 'اپنے ایونٹ کے لیے وینڈرز بک کرنا شروع کریں',
  noStatusBookings: 'اس وقت کوئی بکنگ موجود نہیں',
  createAccount: 'اپنا اکاؤنٹ بنائیں',
  registerBusiness: 'اپنا کاروبار رجسٹر کریں',
  fullName: 'پورا نام',
  emailAddress: 'ای میل ایڈریس',
  phoneNumber: 'فون نمبر',
  password: 'پاس ورڈ',
  confirmPassword: 'پاس ورڈ کی تصدیق کریں',
  signUp: 'سائن اپ کریں',
  creatingAccount: 'اکاؤنٹ بنایا جا رہا ہے...',
  alreadyHaveAccount: 'پہلے سے اکاؤنٹ موجود ہے؟',
  loginHere: 'یہاں لاگ اِن کریں',
  forgotPassword: 'پاس ورڈ بھول گئے؟',
  preferences: 'ترجیحات',
  privacySecurity: 'پرائیویسی اور سیکیورٹی',
  appNotifications: 'ایپ نوٹیفکیشنز',
  receiveAlerts: 'نئے آرڈرز اور پیغامات کی اطلاع حاصل کریں',
  settings: 'سیٹنگز',
  saveSettings: 'سیٹنگز محفوظ کریں',
  aboutMe: 'میرے بارے میں',
  myBookings: 'میری بکنگز',
  paymentMethods: 'ادائیگی کے طریقے',
  helpCenter: 'ہیلپ سینٹر',
  logOut: 'لاگ آؤٹ',
  deleteAccount: 'اکاؤنٹ مستقل طور پر حذف کریں',
  banquets: 'بینکویٹس',
  catering: 'کیٹرنگ',
  photoShoot: 'فوٹو شوٹ',
  parlor: 'پارلر',
  searchPlaceholder: 'وینڈیوز، کیٹرنگ، پارلرز تلاش کریں...',
}

const punjabi: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'زبان چنو',
  appLanguage: 'ایپ دی زبان',
  save: 'محفوظ کرو',
  cancel: 'منسوخ کرو',
  bookRoleTitle: 'میں بک کرنا چاہندا واں',
  vendorRoleTitle: 'میں وینڈر آں',
  continueAsGuest: 'مہمان دے طور تے جاری رکھو',
  currentLocation: 'موجودہ مقام',
  locationUnavailable: 'مقام دستیاب نئیں',
  detectingLocation: 'مقام لبھیا جا رہیا اے...',
  all: 'سارے',
  categories: 'اقسام',
  live: 'لائیو',
  topRated: 'سب توں ودھیا',
  nearbyVendors: 'قریبی وینڈرز',
  seeAll: 'سارے ویکھو',
  loadingVendors: 'وینڈرز لوڈ ہو رہے نیں...',
  startingFrom: 'شروع قیمت',
  guests: 'مہمان',
  dashboard: 'ڈیش بورڈ',
  totalRevenue: 'کل کمائی',
  confirmedBookings: 'پکی بکنگز',
  accepted: 'قبول شدہ',
  rejected: 'مسترد',
  pending: 'التوا اچ',
  myBookingsTitle: 'میریاں بکنگز',
  createAccount: 'اپنا کھاتہ بناؤ',
  fullName: 'پورا ناں',
  signUp: 'سائن اپ کرو',
  loginHere: 'ایتھے لاگ اِن کرو',
  forgotPassword: 'پاس ورڈ بھل گئے؟',
  settings: 'سیٹنگز',
  logOut: 'لاگ آؤٹ',
}

const sindhi: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'ٻولي چونڊيو',
  appLanguage: 'ايپ جي ٻولي',
  save: 'محفوظ ڪريو',
  cancel: 'منسوخ ڪريو',
  bookRoleTitle: 'مان بک ڪرڻ چاهيان ٿو',
  vendorRoleTitle: 'مان وينڊر آهيان',
  continueAsGuest: 'مهمان طور جاري رکو',
  currentLocation: 'موجوده هنڌ',
  locationUnavailable: 'هنڌ دستياب ناهي',
  all: 'سڀ',
  categories: 'قسمون',
  live: 'لائيو',
  topRated: 'بهترين ريٽيڊ',
  nearbyVendors: 'قريپي وينڊرز',
  seeAll: 'سڀ ڏسو',
  guests: 'مهمان',
  dashboard: 'ڊيش بورڊ',
  totalRevenue: 'ڪل آمدني',
  accepted: 'قبول ٿيل',
  rejected: 'رد ٿيل',
  pending: 'التوا ۾',
  createAccount: 'پنهنجو اڪائونٽ ٺاهيو',
  fullName: 'پورو نالو',
  signUp: 'سائن اپ ڪريو',
  loginHere: 'هتي لاگ ان ڪريو',
  forgotPassword: 'پاسورڊ وسري ويو؟',
  settings: 'سيٽنگون',
  logOut: 'لاگ آئوٽ',
}

const pashto: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'ژبه غوره کړئ',
  appLanguage: 'د اپلیکیشن ژبه',
  save: 'خوندي کړئ',
  cancel: 'لغوه کړئ',
  bookRoleTitle: 'زه غواړم بک کړم',
  vendorRoleTitle: 'زه پلورونکی یم',
  continueAsGuest: 'د میلمه په توګه دوام ورکړئ',
  currentLocation: 'اوسنی موقعیت',
  locationUnavailable: 'موقعیت شتون نلري',
  all: 'ټول',
  categories: 'کټګورۍ',
  live: 'ژوندی',
  topRated: 'غوره درجه بندي',
  nearbyVendors: 'نږدې وینڈرز',
  seeAll: 'ټول وګورئ',
  guests: 'میلمانه',
  dashboard: 'ډشبورډ',
  totalRevenue: 'ټول عاید',
  accepted: 'منل شوی',
  rejected: 'رد شوی',
  pending: 'پاتې',
  createAccount: 'خپل حساب جوړ کړئ',
  fullName: 'بشپړ نوم',
  signUp: 'نوم لیکنه وکړئ',
  loginHere: 'دلته ننوتل',
  forgotPassword: 'پټنوم مو هیر شوی؟',
  settings: 'تنظیمات',
  logOut: 'وتل',
}

const balochi: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'زبان گچین کن',
  appLanguage: 'ایپ ءِ زبان',
  save: 'محفوظ کن',
  cancel: 'کینسل کن',
  all: 'درست',
  categories: 'کسماں',
  nearbyVendors: 'نزیکیں وینڈرز',
  logOut: 'لاگ آؤٹ',
}

const saraiki: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'زبان چُݨو',
  appLanguage: 'ایپ دی زبان',
  save: 'محفوظ کرو',
  cancel: 'منسوخ کرو',
  all: 'سارے',
}

const hindko: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'زبان چُݨو',
  appLanguage: 'ایپ دی زبان',
  save: 'محفوظ کرو',
  cancel: 'منسوخ کرو',
  all: 'سارے',
}

const kashmiri: Record<string, string> = {
  ...urdu,
  chooseLanguage: 'زبان ژارۍ',
  appLanguage: 'ایپٕچ زبان',
  save: 'محفوظ کٔرِو',
  cancel: 'منسوخ کٔرِو',
}

const catalogs: Record<LanguageCode, Record<string, string>> = {
  en: english,
  ur: urdu,
  pa: punjabi,
  sd: sindhi,
  ps: pashto,
  bal: balochi,
  skr: saraiki,
  hnd: hindko,
  ks: kashmiri,
}

export const getLanguageLabel = (code: LanguageCode) =>
  LANGUAGE_OPTIONS.find((option) => option.code === code)?.nativeLabel || 'English'

export const translate = (language: LanguageCode, key: string) => {
  return catalogs[language]?.[key] || english[key] || key
}
