export type LanguageCode = 'en' | 'ur' | 'pa' | 'sd' | 'ps' | 'bal' | 'skr' | 'hnd' | 'ks'

export type LanguageOption = {
  code: LanguageCode
  label: string
  nativeLabel: string
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'پنجابی' },
  { code: 'sd', label: 'Sindhi', nativeLabel: 'سنڌي' },
  { code: 'ps', label: 'Pashto', nativeLabel: 'پښتو' },
  { code: 'bal', label: 'Balochi', nativeLabel: 'بلوچی' },
  { code: 'skr', label: 'Saraiki', nativeLabel: 'سرائیکی' },
  { code: 'hnd', label: 'Hindko', nativeLabel: 'ہندکو' },
  { code: 'ks', label: 'Kashmiri', nativeLabel: 'کٲشُر' },
]

const urdu: Record<string, string> = {
  chooseLanguage: 'زبان منتخب کریں',
  appLanguage: 'ایپ کی زبان',
  save: 'محفوظ کریں',
  cancel: 'منسوخ کریں',
  welcomeSubtitleClient: 'ویڈیوز، کھانا، ڈیکور اور مزید بک کریں۔',
  welcomeSubtitleVendor: 'سروسز شامل کریں اور آرڈرز حاصل کریں۔',
  bookRoleTitle: 'میں بک کرنا چاہتا/چاہتی ہوں',
  vendorRoleTitle: 'میں وینڈر ہوں',
  continueAsGuest: 'بطور مہمان جاری رکھیں',
  guestDescription: 'بغیر سائن اپ کے وینڈرز، پیکیجز اور فیچرز دیکھیں۔',
  currentLocation: 'موجودہ مقام',
  locationUnavailable: 'مقام دستیاب نہیں',
  detectingLocation: 'مقام معلوم کیا جا رہا ہے...',
  all: 'سب',
  categories: 'اقسام',
  live: 'فعال',
  topRated: 'بہترین ریٹیڈ',
  seeAll: 'سب دیکھیں',
  loadingVendors: 'وینڈرز لوڈ ہو رہے ہیں...',
  startingFrom: 'شروع قیمت',
  guests: 'مہمان',
  guestModeTitle: 'گیسٹ موڈ میں بکنگ بند ہے',
  signInToUseChat: 'چیٹ استعمال کرنے کے لیے سائن اِن کریں۔',
  dashboard: 'ڈیش بورڈ',
  vendorControlPanel: 'وینڈر کنٹرول پینل',
  totalRevenue: 'کل آمدنی',
  confirmedBookings: 'کنفرم شدہ بکنگز',
  accepted: 'قبول شدہ',
  rejected: 'مسترد',
  pending: 'زیر التوا',
  avgRating: 'اوسط ریٹنگ',
  pendingBookings: 'زیر التوا بکنگز',
  loadingRecentOrders: 'حالیہ آرڈرز لوڈ ہو رہے ہیں...',
  noPendingBookings: 'کوئی زیر التوا بکنگ نہیں',
  recentReviews: 'حالیہ جائزے',
  myBookingsTitle: 'میری بکنگز',
  trackBookings: 'اپنی ایونٹ بکنگز کو ٹریک اور منظم کریں',
  bookingsLocked: 'گیسٹ موڈ میں بکنگز بند ہیں',
  signInToViewBookings: 'اپنی بکنگز دیکھنے اور منظم کرنے کے لیے سائن اِن کریں۔',
  youAreGuest: 'آپ بطور مہمان براؤز کر رہے ہیں',
  bookingHistoryAfterSignIn: 'بکنگ ہسٹری اور منیجمنٹ سائن اِن کے بعد دستیاب ہیں۔',
  loadingBookings: 'بکنگز لوڈ ہو رہی ہیں...',
  noBookingsFound: 'کوئی بکنگ نہیں ملی',
  startBooking: 'اپنے ایونٹ کے لیے وینڈرز بک کرنا شروع کریں',
  noStatusBookings: 'اس وقت کوئی بکنگ موجود نہیں',
  createAccount: 'اپنا اکاؤنٹ بنائیں',
  registerBusiness: 'اپنا کاروبار رجسٹر کریں',
  fullName: 'پورا نام',
  emailAddress: 'ای میل ایڈریس',
  phoneNumber: 'فون نمبر',
  password: 'پاس ورڈ',
  confirmPassword: 'پاس ورڈ کی تصدیق کریں',
  signUp: 'سائن اپ کریں',
  creatingAccount: 'اکاؤنٹ بنایا جا رہا ہے...',
  alreadyHaveAccount: 'پہلے سے اکاؤنٹ موجود ہے؟',
  loginHere: 'یہاں لاگ اِن کریں',
  forgotPassword: 'پاس ورڈ بھول گئے؟',
  preferences: 'ترجیحات',
  privacySecurity: 'پرائیویسی اور سیکیورٹی',
  appNotifications: 'ایپ نوٹیفکیشنز',
  receiveAlerts: 'نئے آرڈرز اور پیغامات کی اطلاع حاصل کریں',
  settings: 'سیٹنگز',
  saveSettings: 'سیٹنگز محفوظ کریں',
  aboutMe: 'میرے بارے میں',
  myBookings: 'میری بکنگز',
  paymentMethods: 'ادائیگی کے طریقے',
  helpCenter: 'ہیلپ سینٹر',
  logOut: 'لاگ آؤٹ',
  deleteAccount: 'اکاؤنٹ مستقل طور پر حذف کریں',
}

const english: Record<string, string> = {
  chooseLanguage: 'Choose language',
  appLanguage: 'App language',
  save: 'Save',
  cancel: 'Cancel',
  welcomeSubtitleClient: 'Book venues, food, decor & more.',
  welcomeSubtitleVendor: 'List services & get orders.',
  bookRoleTitle: 'I want to Book',
  vendorRoleTitle: 'I am a Vendor',
  continueAsGuest: 'Continue as Guest',
  guestDescription: 'Explore vendors, packages, and features without signing up.',
  currentLocation: 'Current Location',
  locationUnavailable: 'Location unavailable',
  detectingLocation: 'Detecting location...',
  all: 'All',
  categories: 'Categories',
  live: 'Live',
  topRated: 'Top Rated',
  seeAll: 'See All',
  loadingVendors: 'Loading vendors...',
  startingFrom: 'Starting From',
  guests: 'Guests',
  guestModeTitle: 'Bookings locked in guest mode',
  signInToUseChat: 'Sign in to use chat features.',
  dashboard: 'Dashboard',
  vendorControlPanel: 'Vendor Control Panel',
  totalRevenue: 'Total Revenue',
  confirmedBookings: 'Confirmed Bookings',
  accepted: 'Accepted',
  rejected: 'Rejected',
  pending: 'Pending',
  avgRating: 'Avg Rating',
  pendingBookings: 'Pending Bookings',
  loadingRecentOrders: 'Loading recent orders...',
  noPendingBookings: 'No pending bookings',
  recentReviews: 'Recent Reviews',
  myBookingsTitle: 'My Bookings',
  trackBookings: 'Track and manage your event bookings',
  bookingsLocked: 'Bookings locked in guest mode',
  signInToViewBookings: 'Sign in to view and manage your bookings.',
  youAreGuest: 'You are browsing as a guest',
  bookingHistoryAfterSignIn: 'Booking history and booking management are available after sign in.',
  loadingBookings: 'Loading bookings...',
  noBookingsFound: 'No bookings found',
  startBooking: 'Start booking vendors for your event',
  noStatusBookings: 'No bookings at the moment',
  createAccount: 'Create Your Account',
  registerBusiness: 'Register Your Business',
  fullName: 'Full Name',
  emailAddress: 'Email Address',
  phoneNumber: 'Phone Number',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  signUp: 'Sign Up',
  creatingAccount: 'Creating account...',
  alreadyHaveAccount: 'Already have an account?',
  loginHere: 'Login Here',
  forgotPassword: 'Forgot Password?',
  preferences: 'Preferences',
  privacySecurity: 'Privacy & Security',
  appNotifications: 'App Notifications',
  receiveAlerts: 'Receive alerts for new orders and messages',
  settings: 'Settings',
  saveSettings: 'Save Settings',
  aboutMe: 'About Me',
  myBookings: 'My Bookings',
  paymentMethods: 'Payment Methods',
  helpCenter: 'Help Center',
  logOut: 'Log Out',
  deleteAccount: 'Delete Account Permanently',
}

const catalogs: Record<LanguageCode, Record<string, string>> = {
  en: english,
  ur: urdu,
  pa: english,
  sd: english,
  ps: english,
  bal: english,
  skr: english,
  hnd: english,
  ks: english,
}

export const getLanguageLabel = (code: LanguageCode) =>
  LANGUAGE_OPTIONS.find((option) => option.code === code)?.nativeLabel || 'English'

export const translate = (language: LanguageCode, key: string) => {
  return catalogs[language]?.[key] || english[key] || key
}
